- hosts: all
  become: yes
  roles:
    - docker

- name: Deploy Backend Service
  hosts: group_backend
  become: yes
  roles:
    - backend

- name: Deploy Frontend Service
  hosts: group_frontend
  become: yes
  roles:
    - frontend